policy:
  id: "sshd_misconfiguration"
  file: "sshd_misconfiguration.yml"
  name: "sshd_misconfiguration"
  description: "Sets of checks for sshd configuration"

variables:
  $sshd_file: /etc/ssh/sshd_config

requirements:
  title: "Check whether it's linux and sshd_config exists"
  description: ""
  condition: all
  rules:
    - "f:/proc/sys/kernel/ostype -> Linux"
    - "f:$sshd_file"

checks:
  - id: 1
    title: "SSH Hardening: Password authentication should be disabled"
    description: "SSH Daemon should reject passwords during authentication"
    remediation: "Set config line: 'PasswordAuthentication no' in /etc/ssh/sshd_config file"
    condition: all
    rules:
      - "f:$sshd_file -> r:^PasswordAuthentication no"
  - id: 2
    title: "SSH Hardening: Root user should not be allowed for login"
    description: "SSH Daemon should reject root login"
    remediation: "Set config line: 'PermitRootLogin no' in /etc/ssh/sshd_config file"
    condition: all
    rules:
      - "f:$sshd_file -> r:^PermitRootLogin no"
